/**************************************************************************************************************************************************
                        Business Purpose    -    Extracting only the url from website
                        Invoke function     -    staging_test.cdp.url(url as parameter)
                                                 eg: select staging_test.cdp.url('https://peninsuladermatology.com')
                        Dependencies        -    Dependent on source table's url field only

                        Version History     -    01/02/2024 - V_01 - Created - Parker | Senthil
                                                 01/25/2024 - V_02 - Updates- Alex Ennis
***************************************************************************************************************************************************/


CREATE OR REPLACE FUNCTION STAGING_DEV.CDP.TEST_URL("website" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
AS $$
 
CASE WHEN lower(website) ILIKE '%linkedin.com' THEN null
     WHEN lower(website) ILIKE '%linkedin%' THEN  (CASE WHEN lower(website) iLIKE 'http://www%' THEN SUBSTRING(CASE WHEN lower(website) ilike '%?trk%' then split_part(lower(website), '?trk',1)
                                                                                                         WHEN lower(website) ilike '%/?original%' then split_part(lower(website), '/?original', 1)
                                                                                                         WHEN lower(website) ilike '%/' then SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                     else lower(website) 
                                                                                                     end, 12)
                                                WHEN lower(website) iLIKE 'https://www%' THEN SUBSTRING(CASE WHEN lower(website) ilike '%?trk%' then split_part(lower(website), '?trk',1)
                                                                                                        WHEN lower(website) ilike '%/?original%' then split_part(lower(website), '/?original', 1)
                                                                                                        WHEN lower(website) ilike '%/' then SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                     else lower(website) 
                                                                                                     end, 13)
                                                WHEN lower(website) iLIKE 'www%' THEN SUBSTRING(CASE WHEN lower(website) ilike '%?trk%' then split_part(lower(website), '?trk',1)
                                                                                                WHEN lower(website) ilike '%/?original%' then split_part(lower(website), '/?original', 1)
                                                                                                WHEN lower(website) ilike '%/' then SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                
                                                                                                     else lower(website) 
                                                                                                     end, 5)
                                                WHEN lower(website) iLIKE 'https://%' THEN SUBSTRING(CASE WHEN lower(website) ilike '%?trk%' then split_part(lower(website), '?trk',1)
                                                                                                WHEN lower(website) ilike '%/?original%' then split_part(lower(website), '/?original', 1)
                                                                                                WHEN lower(website) ilike '%/' then SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                
                                                                                                     else lower(website) 
                                                                                                     end, 9)
                                                WHEN lower(website) ILIKE '%linkedin.com' then null
                                                ELSE lower(website) 
                                                END
                                           )
    WHEN lower(website) ILIKE '%instagram.com' THEN null                                      
    WHEN lower(website) ilike '%instagram%' then (CASE WHEN lower(website) ILIKE 'dermwatts.com %' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                            WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website))- 7)
                                                                                                            WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                            WHEN lower(website) ILIKE '%/reels' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                            WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                            WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                            WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                            WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                          ELSE lower(website) end), 28)
                                                WHEN lower(website) ILIKE 'www.dermadarling%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                            WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                            WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                            WHEN lower(website) ILIKE '%/reels' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                            WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                            WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                            WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                            WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                          ELSE lower(website) end), 34)
                                                WHEN lower(website) iLIKE 'http://www%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                      WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                      WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                      WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                      WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                      WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                      WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                      WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                          ELSE lower(website) end), 12)
                                                WHEN lower(website) iLIKE 'https://www%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                       WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                       WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                       WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                       WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                       WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                       WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                       WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                          ELSE lower(website) end), 13)
                                                WHEN lower(website) iLIKE 'www%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                               WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                               WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                               WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                               WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                               WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                               WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                               WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                          ELSE lower(website) end), 5)
                                                WHEN lower(website) ILIKE 'HTTPS://%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                    WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                    WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                    WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                    WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                    WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                    WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                    WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                          ELSE lower(website) end), 9)
                                                WHEN lower(website) ILIKE 'HTTP://%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'?ref=page',1)
                                                                                                          ELSE lower(website) end), 8)
                                                WHEN lower(website) ILIKE 'winecoutryaest%' then 'instagram.com/Winecountryaestheticnurse'
                                                WHEN lower(website) ILIKE '%instagram.com' then null
                                                WHEN lower(website) ILIKE '%instagram.com/' then null
                                                ELSE lower(website) 
                                                END)
    WHEN lower(website) ILIKE '%facebook.com' THEN null
    WHEN lower(website) ilike '%facebook%' then (
                                           CASE WHEN lower(website) ILIKE 'https://pt-br.%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 15)
                                                WHEN lower(website) ILIKE 'https://ne-np.%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 15)
                                                WHEN lower(website) ILIKE 'https://en-gb.%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 15)
                                                WHEN lower(website) ILIKE 'https://hi-in.%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 15)
                                                WHEN lower(website) ILIKE 'https://ms-my.%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 15)
                                                WHEN lower(website) ILIKE 'https://m.%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 11)
                                                WHEN lower(website) ILIKE 'www.HTTPs://%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 15)
                                                WHEN lower(website) iLIKE 'http://www%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                      WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                      WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                      WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                      WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                      WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                      WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                      WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                      WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                      WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                      WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                      WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                      WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                      WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                      WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                      WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                      WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                      WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                      WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                      WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 12)
                                                WHEN lower(website) iLIKE 'https://www%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                       WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                       WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                       WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                       WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                       WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                       WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                       WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                       WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                       WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                       WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                       WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                       WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                       WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                       WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                       WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                       WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                       WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                       WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                       WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 13)
                                                WHEN lower(website) iLIKE 'www%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                               WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                               WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                               WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                               WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                               WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                               WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                               WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                               WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                               WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                               WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                               WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                               WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                               WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                               WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                               WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                               WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                               WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                               WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                               WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 5)
                                                WHEN lower(website) ILIKE 'HTTPS://%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                    WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                    WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                    WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                    WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                    WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                    WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                    WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                    WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                    WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                    WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                    WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                    WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                    WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                    WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                    WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                    WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                    WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                    WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                    WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 9)
                                                WHEN lower(website) ILIKE 'HTTP://%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 8)
                                                WHEN lower(website) ILIKE 'www.HTTPs://%' THEN SUBSTRING((CASE WHEN lower(website) ILIKE '%/reels/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 13)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=en' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/?hl=bg' THEN SUBSTRING(lower(website),1, length(lower(website)) - 7)
                                                                                                   WHEN lower(website) ILIKE '%/reels%' THEN SUBSTRING (lower(website),1, length(lower(website)) - 6)
                                                                                                   WHEN lower(website) ILIKE '%/services%' THEN split_part(lower(website),'/services',1)
                                                                                                   WHEN lower(website) ilike '%/?igshid=%' THEN split_part(lower(website), '/?', 1)
                                                                                                   WHEN lower(website) ilike '%?igshid=%' THEN split_part(lower(website), '?', 1)
                                                                                                   WHEN lower(website) ilike '%?utm_%' THEN split_part(lower(website), '?utm_', 1)
                                                                                                   WHEN lower(website) ilike '%?mibex%' THEN split_part(lower(website),'?mibex', 1)
                                                                                                   WHEN lower(website) ilike '%&mibex%' THEN split_part(lower(website),'&mibex', 1)
                                                                                                   WHEN lower(website) ilike '%/about%' THEN split_part(lower(website), '/about',1)
                                                                                                   WHEN lower(website) ILIKE '%/?paipv%' THEN split_part(lower(website),'/?paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%?fref%' THEN split_part(lower(website),'?fref',1)
                                                                                                   WHEN lower(website) ILIKE '%/mentions' THEN split_part(lower(website),'/mentions',1)
                                                                                                   WHEN lower(website) ILIKE '%&paipv%' THEN split_part(lower(website),'&paipv',1)
                                                                                                   WHEN lower(website) ILIKE '%/?locale%' THEN split_part(lower(website), '/?locale', 1)
                                                                                                   WHEN lower(website) ILIKE '%/photos_by' THEN split_part(lower(website), '/photos_by',1)
                                                                                                   WHEN lower(website) ILIKE '%&sk=abo%' THEN split_part(lower(website), '&sk=about',1)
                                                                                                   WHEN lower(website) ILIKE '%/' THEN SUBSTRING (lower(website),1, length(lower(website)) -1)
                                                                                                   WHEN lower(website) ilike '%?ref=page%' THEN split_part(lower(website),'/?ref=page',1)
                                                                                                          ELSE lower(website) end), 13)
                                                

                                                ELSE lower(website) 
                                                END)
    ELSE TRIM(REGEXP_REPLACE(lower(website), '[a-zA-Z]+://|[a-zA-Z]+:/|www\\.|/[^)]*|https?:', ''))
    END
    $$;
